#!/usr/bin/env python3
"""Rebuild the Lab 2 source snapshot, checksums, and submission ZIP."""

from pathlib import Path
import hashlib
import shutil
import subprocess
import zipfile


ROOT = Path(__file__).resolve().parents[1]
BUNDLE = ROOT / 'submission' / 'lab2_hw3214'
SOURCE = BUNDLE / 'source' / 'prob_rob_labs_ros_2'
SOURCE_FOLDERS = ('models', 'prob_rob_labs', 'prob_rob_msgs', 'vision', 'tools')
CACHE_FOLDERS = {'__pycache__', '.pytest_cache'}


def main():
    required = [
        BUNDLE / 'START_HERE.txt',
        BUNDLE / 'report' / 'lab2_report.docx',
        BUNDLE / 'report' / 'lab2_report.pdf',
        BUNDLE / 'video' / 'lab2_assignment3_trimmed.mp4',
        BUNDLE / 'video' / 'trim_details.json',
        BUNDLE / 'evidence' / 'speed_summary.csv',
    ]
    for speed in ('0.3', '0.6', '0.8'):
        required.extend([
            BUNDLE / 'evidence' / 'raw' / f'speed-{speed}.txt',
            BUNDLE / 'evidence' / 'trimmed' / f'speed-{speed}-steady.txt',
        ])
    missing = [str(path.relative_to(ROOT)) for path in required if not path.is_file()]
    if missing:
        raise SystemExit('Missing submission files: ' + ', '.join(missing))

    # This directory is generated by this script, never the working source tree.
    if SOURCE.exists():
        shutil.rmtree(SOURCE)
    SOURCE.mkdir(parents=True)
    for folder in SOURCE_FOLDERS:
        for path in sorted((ROOT / folder).rglob('*')):
            if (not path.is_file() or CACHE_FOLDERS.intersection(path.parts)
                    or path.suffix in ('.pyc', '.pyo')):
                continue
            destination = SOURCE / path.relative_to(ROOT)
            destination.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(path, destination)
    shutil.copy2(ROOT / 'LICENSE', SOURCE / 'LICENSE')
    commit = subprocess.check_output(
        ['git', 'rev-parse', 'HEAD'], cwd=ROOT, text=True).strip()
    (SOURCE / 'SOURCE_NOTES.txt').write_text(
        f'Lab 2 source snapshot — Howard Wang (hw3214)\n'
        f'Git HEAD at packaging: {commit}\n'
        'Snapshot includes current working-tree files, including uncommitted edits.\n'
        'Use as the sole copy of these packages in a configured ROS 2 workspace.\n'
        'Do not nest it in another checkout or duplicate packages under src/.\n'
        'No generated workspace output, Git metadata, or Python caches included.\n',
        encoding='utf-8')

    manifest = BUNDLE / 'MANIFEST.sha256'
    files = sorted(path for path in BUNDLE.rglob('*')
                   if path.is_file() and path != manifest)
    manifest.write_text(''.join(
        hashlib.sha256(path.read_bytes()).hexdigest() + '  '
        + path.relative_to(BUNDLE).as_posix() + '\n' for path in files),
        encoding='utf-8')

    archive = BUNDLE.parent / 'lab2_hw3214_submission.zip'
    temporary = archive.with_suffix('.zip.tmp')
    with zipfile.ZipFile(temporary, 'w', zipfile.ZIP_DEFLATED) as output:
        for path in sorted(BUNDLE.rglob('*')):
            if path.is_file():
                output.write(path, path.relative_to(BUNDLE.parent))
    with zipfile.ZipFile(temporary) as check:
        if check.testzip() is not None:
            raise RuntimeError('Submission ZIP failed its integrity check')
        for line in manifest.read_text(encoding='utf-8').splitlines():
            digest, relative = line.split('  ', 1)
            if hashlib.sha256(check.read(f'{BUNDLE.name}/{relative}')).hexdigest() != digest:
                raise RuntimeError(f'Checksum mismatch: {relative}')
    temporary.replace(archive)
    print(f'Created {archive.relative_to(ROOT)} ({archive.stat().st_size:,} bytes)')
    print('Report placeholders for Assignments 1–2 still need teammate input.')


if __name__ == '__main__':
    main()
